name: pages

on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2

#      - uses: purescript-contrib/setup-purescript@main

      - name: Cache PureScript dependencies
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-spago-${{ hashFiles('**/*.dhall') }}
          path: |
            model/.spago
            model/output
            model/node_modules
            annotation-tool/.spago
            annotation-tool/output
            annotation-tool/node_modules
            viewer/.spago
            viewer/output
            viewer/node_modules

      - name: Install build dependencies
        run: cd annotation-tool; npm install
            
      - name: Build
        run: cd annotation-tool; npm run build-prod

      - name: Deploy build
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./annotation-tool/dist
